version: '2.1'

services:
  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile
    restart: always
    container_name: osh_backend
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./db/db.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.2
    restart: always
    container_name: osh_db
    env_file:
      - ./db/db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
